version: "3.8"

services:
  jupyterlab:
    image: chamidullinr/jupyterlab:1.0.0
    build:
      context: .
      args:
        - PYTHON_VERSION=3.9
        - CREATE_R_CONDA_ENV=no
        - INSTALL_GIT_LFS=yes
        - INSTALL_AWS_CLI=no
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - "jupyter-data:/root/.jupyter"
#    network_mode: "host"
    ipc: "host"
    user: root
    environment:
      - "GRANT_SUDO=yes"
      - "NB_USER=jovyan"
      - "CHOWN_HOME=yes"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "12g"

volumes:
  jupyter-data:
