version: "3.8"

services:
  jupyter-ml:
    image: chamidullinr/jupyter-ml
    build: .
    container_name: jupyter-ml
    volumes:
        - ~/Projects:/Projects
    ports:
      - "8888:8888"
    environment:
      - "GRANT_SUDO=yes"
      - "NB_USER=jovyan"
      - "CHOWN_HOME=yes"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "12g"
