version: "3.8"

services:
  jupyter-ml:
    image: chamidullinr/jupyter-ml
    build:
      context: .
      args:
        - PYTHON_VERSION=3.9
        - CREATE_R_CONDA_ENV=no
        - INSTALL_GIT_LFS=yes
        - INSTALL_AWS_CLI=no
    container_name: jupyter-ml
    ports:
      - "8888:8888"
#    network_mode: "host"
    ipc: "host"
    user: root
    environment:
      - "GRANT_SUDO=yes"
      - "NB_USER=jovyan"
      - "CHOWN_HOME=yes"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "12g"
