version: "3.8"

services:
  pypiserver:
    image: pypiserver/pypiserver:latest
    container_name: pypiserver
    volumes:
        - ./auth:/data/auth
        - packages-data:/data/packages
    ports:
      - "8080:8080"
    command: -P /data/auth/.htpasswd -a update /data/packages

volumes:
  packages-data:
